name: final-cicd-tags

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      - uses: golangci/golangci-lint-action@v3

  tests:
    need: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test ./...