name: Lint Go code

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23' # Specify the Go version you need

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test ./...